import { useNavigate } from 'react-router-dom'
import PublicNav from '../../public/PublicNav'
import PublicFooter from '../../public/PublicFooter'
import { C, FONT, MAX_WIDTH } from '../../constants'

function Section({ title, children }) {
  return (
    <section style={{ marginBottom: 36 }}>
      <h2 style={{ fontFamily: FONT, fontSize: 18, fontWeight: 800, color: C.dark, marginBottom: 12, marginTop: 0 }}>
        {title}
      </h2>
      <div style={{ fontFamily: FONT, fontSize: 15, color: C.gray5, lineHeight: 1.75 }}>
        {children}
      </div>
    </section>
  )
}

export default function PrivacyPolicy() {
  const nav = useNavigate()

  return (
    <div style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column' }}>
      <PublicNav />

      <main style={{ flex: 1, padding: '108px 20px 60px', maxWidth: MAX_WIDTH, margin: '0 auto', width: '100%' }}>

        {/* Back */}
        <button
          onClick={() => nav(-1)}
          style={{ background: 'none', border: 'none', cursor: 'pointer', color: C.green, fontFamily: FONT, fontSize: 13, fontWeight: 600, padding: 0, marginBottom: 24, display: 'flex', alignItems: 'center', gap: 4 }}
        >
          ← Back
        </button>

        <h1 style={{ fontFamily: FONT, fontSize: 28, fontWeight: 900, color: C.dark, marginBottom: 6, marginTop: 0 }}>
          Privacy Policy
        </h1>
        <p style={{ fontFamily: FONT, fontSize: 13, color: C.gray3, marginBottom: 36 }}>
          Last updated: June 2025 · Applies to tucc.club
        </p>

        <Section title="1. Who We Are">
          <p>
            This privacy policy applies to the Tamil United Cricket Club member portal at tucc.club
            (the "App"), operated by <strong>Dollishill Tamil United</strong>, registered at{' '}
            <strong>27 Orchard Gate, Greenford, Middlesex, UB6 0QL</strong>, United Kingdom ("we", "us", "the Club").
          </p>
          <p style={{ marginTop: 10 }}>
            Contact us about privacy matters at: <strong>info@tucc.club</strong>
          </p>
        </Section>

        <Section title="2. What Data We Collect">
          <p><strong>Account &amp; identity data</strong></p>
          <ul style={{ paddingLeft: 20, marginTop: 6, marginBottom: 12 }}>
            <li>Full name, email address, phone number</li>
            <li>Playing role (batsman, bowler, etc.) and shirt number</li>
            <li>Profile photograph (if uploaded voluntarily)</li>
          </ul>

          <p><strong>Cricket activity data</strong></p>
          <ul style={{ paddingLeft: 20, marginTop: 6, marginBottom: 12 }}>
            <li>Match statistics: runs, wickets, catches, innings played, averages, strike rates</li>
            <li>Match availability responses (available / unavailable / maybe)</li>
            <li>Player of the Week nominations</li>
            <li>Batting and bowling analysis scores generated by the App</li>
          </ul>

          <p><strong>Usage &amp; technical data</strong></p>
          <ul style={{ paddingLeft: 20, marginTop: 6, marginBottom: 12 }}>
            <li>IP address, browser type, operating system, device type</li>
            <li>Pages viewed, buttons clicked, session duration (activity log for admins)</li>
            <li>Authentication tokens stored in browser localStorage (Supabase Auth)</li>
          </ul>

          <p><strong>Gallery &amp; media</strong></p>
          <ul style={{ paddingLeft: 20, marginTop: 6 }}>
            <li>Photos and videos uploaded by club members to the gallery</li>
            <li>AI-generated captions for uploaded media (titles created by Anthropic Claude)</li>
          </ul>
        </Section>

        <Section title="3. Why We Process Your Data (Legal Basis)">
          <p>We rely on the following lawful bases under UK GDPR:</p>
          <ul style={{ paddingLeft: 20, marginTop: 6 }}>
            <li>
              <strong>Legitimate interests</strong> — managing club membership, selecting teams,
              tracking match results and league standings, communicating with members about
              fixtures and availability. These are necessary for running the cricket club.
            </li>
            <li style={{ marginTop: 8 }}>
              <strong>Contract</strong> — processing data necessary to fulfil club membership
              obligations (e.g. fixture notifications, team selection communications).
            </li>
            <li style={{ marginTop: 8 }}>
              <strong>Consent</strong> — for optional features: uploading your profile photo,
              appearing in the gallery, and AI-generated player profile descriptions. You may
              withdraw consent at any time by contacting us.
            </li>
            <li style={{ marginTop: 8 }}>
              <strong>Legal obligation</strong> — if required by BTCL UK league rules or
              applicable law.
            </li>
          </ul>
        </Section>

        <Section title="4. Who We Share Data With (Data Processors)">
          <p>We use the following third-party processors. All are subject to data processing agreements:</p>

          <table style={{ width: '100%', borderCollapse: 'collapse', marginTop: 12, fontSize: 13 }}>
            <thead>
              <tr style={{ background: C.gray1 }}>
                <th style={{ padding: '8px 12px', textAlign: 'left', borderBottom: `1px solid ${C.gray2}` }}>Processor</th>
                <th style={{ padding: '8px 12px', textAlign: 'left', borderBottom: `1px solid ${C.gray2}` }}>Purpose</th>
                <th style={{ padding: '8px 12px', textAlign: 'left', borderBottom: `1px solid ${C.gray2}` }}>Location</th>
              </tr>
            </thead>
            <tbody>
              {[
                ['Supabase (AWS)', 'Database, authentication, file storage', 'EU / US'],
                ['Vercel Inc.', 'App hosting and serverless functions', 'US (SCCs apply)'],
                ['Resend', 'Transactional email delivery', 'US (SCCs apply)'],
                ['Anthropic PBC', 'AI-generated player profiles and gallery captions', 'US (SCCs apply)'],
                ['BTCL / Play Cricket', 'League fixtures and results (read-only import)', 'UK'],
                ['Open-Meteo', 'Weather forecast for match days (no personal data)', 'EU'],
              ].map(([proc, purpose, loc]) => (
                <tr key={proc} style={{ borderBottom: `1px solid ${C.gray2}` }}>
                  <td style={{ padding: '8px 12px', fontWeight: 600 }}>{proc}</td>
                  <td style={{ padding: '8px 12px' }}>{purpose}</td>
                  <td style={{ padding: '8px 12px', color: C.gray4 }}>{loc}</td>
                </tr>
              ))}
            </tbody>
          </table>

          <p style={{ marginTop: 12, fontSize: 13, color: C.gray4 }}>
            SCCs = Standard Contractual Clauses (EU/UK approved mechanism for international transfers).
          </p>

          <p style={{ marginTop: 12 }}>
            We do not sell your personal data to any third party. We do not use your data for
            advertising or profiling outside of club management.
          </p>
        </Section>

        <Section title="5. How Long We Keep Your Data">
          <ul style={{ paddingLeft: 20, marginTop: 6 }}>
            <li><strong>Member account &amp; statistics</strong> — retained for as long as you are an active member, plus 3 years after your last season, then deleted or anonymised.</li>
            <li style={{ marginTop: 8 }}><strong>Activity logs</strong> — rolling 90-day window (automatically purged).</li>
            <li style={{ marginTop: 8 }}><strong>Gallery media</strong> — retained indefinitely for club archives unless you request removal.</li>
            <li style={{ marginTop: 8 }}><strong>Email communications</strong> — 2 years from last interaction.</li>
          </ul>
        </Section>

        <Section title="6. Your Rights Under UK GDPR">
          <p>You have the right to:</p>
          <ul style={{ paddingLeft: 20, marginTop: 6 }}>
            <li><strong>Access</strong> a copy of your personal data</li>
            <li><strong>Rectification</strong> — correct inaccurate data</li>
            <li><strong>Erasure</strong> — request deletion ("right to be forgotten")</li>
            <li><strong>Restriction</strong> — limit how we process your data</li>
            <li><strong>Portability</strong> — receive your data in a structured, machine-readable format</li>
            <li><strong>Object</strong> — to processing based on legitimate interests</li>
            <li><strong>Withdraw consent</strong> at any time for consent-based processing</li>
          </ul>
          <p style={{ marginTop: 12 }}>
            To exercise any right, email <strong>info@tucc.club</strong>. We will respond within
            30 days. You also have the right to lodge a complaint with the{' '}
            <a href="https://ico.org.uk" target="_blank" rel="noopener noreferrer" style={{ color: C.green }}>
              Information Commissioner's Office (ICO)
            </a>.
          </p>
        </Section>

        <Section title="7. Cookies &amp; Local Storage">
          <p>
            This App does not use tracking or advertising cookies. We use browser{' '}
            <code style={{ background: C.gray1, padding: '2px 6px', borderRadius: 4, fontSize: 13 }}>localStorage</code>{' '}
            solely to store your Supabase authentication session token. See our{' '}
            <button
              onClick={() => nav('/cookies')}
              style={{ background: 'none', border: 'none', color: C.green, cursor: 'pointer', fontFamily: FONT, fontSize: 15, fontWeight: 600, padding: 0 }}
            >
              Cookie Policy
            </button>{' '}
            for details.
          </p>
        </Section>

        <Section title="8. Security">
          <p>
            We implement appropriate technical measures including HTTPS (enforced via HSTS),
            row-level security on the database, environment-variable-managed API keys (not stored
            in client code), and access logging. No system is completely secure; if you believe
            your account has been compromised, contact <strong>info@tucc.club</strong> immediately.
          </p>
        </Section>

        <Section title="9. Children">
          <p>
            This App is intended for club members aged 16 and over. We do not knowingly collect
            data from children under 13. If you believe a child's data has been submitted, please
            contact us and we will delete it promptly.
          </p>
        </Section>

        <Section title="10. Changes to This Policy">
          <p>
            We may update this policy from time to time. Material changes will be notified via the
            App. The "last updated" date at the top of this page indicates when the policy was
            last revised. Continued use of the App after changes constitutes acceptance.
          </p>
        </Section>

      </main>

      <PublicFooter />
    </div>
  )
}
